apiVersion: v1
kind: Service
metadata:
  name: rust-demo
  labels:
    app.kubernetes.io/name: rust-demo
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: rust-demo
  ports:
    - port: 80
      targetPort: http
      name: http
