name: infra-tier-01-environments

on:
  workflow_dispatch:
    inputs:
      apply:
        description: "Apply after plan"
        required: false
        type: boolean
        default: true
  push:
    branches: [main]
    paths:
      - "tier-01-cdktf-environments/**"
  workflow_call:
    inputs:
      apply:
        required: false
        type: boolean
        default: true

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    uses: ./.github/workflows/_infra-shared-cdktf-tier.yml
    with:
      tier_dir: tier-01-cdktf-environments
      stack: devnet
      apply: ${{ inputs.apply == null && true || inputs.apply }}
