name: infra-tier-02-clusters

on:
  workflow_dispatch:
    inputs:
      apply:
        required: false
        type: boolean
        default: true
  push:
    branches: [main]
    paths:
      - "tier-02-cdktf-clusters/**"
  workflow_call:
    inputs:
      apply:
        required: false
        type: boolean
        default: true

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    uses: ./.github/workflows/_infra-shared-cdktf-tier.yml
    with:
      tier_dir: tier-02-cdktf-clusters
      stack: devnet
      apply: ${{ inputs.apply == null && true || inputs.apply }}
