name: infra-tier-03-internal-tools

on:
  workflow_dispatch:
    inputs:
      apply:
        required: false
        type: boolean
        default: true
  push:
    branches: [main]
    paths:
      - "tier-03-cdktf-internal-tools/**"
  workflow_call:
    inputs:
      apply:
        required: false
        type: boolean
        default: true

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    with:
      tier_dir: tier-03-cdktf-internal-tools
      stack: devnet
      apply: ${{ inputs.apply == null && true || inputs.apply }}
